# Generated by Django 2.2 on 2020-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField()),
                ('question', models.TextField(max_length=200)),
                ('qtype', models.TextField(choices=[('OA', 'one_answer'), ('MA', 'multiple_answer')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
