# Generated by Django 2.2 on 2020-02-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qtype',
        ),
    ]
