# Generated by Django 2.2 on 2020-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
