# Generated by Django 2.2 on 2020-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20200224_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_number', models.IntegerField()),
                ('target_areas', models.ManyToManyField(to='interview.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
