# Generated by Django 2.2 on 2020-02-24 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20200224_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
