# Generated by Django 2.2 on 2020-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20200227_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
